#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LazyLoadDataList.Resource", IsApplication=true)]

namespace LazyLoadDataList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LazyLoadDataList.Data.Resource.String.ApplicationName = global::LazyLoadDataList.Resource.String.ApplicationName;
			global::LazyLoadDataList.Data.Resource.String.Hello = global::LazyLoadDataList.Resource.String.Hello;
			global::LazyLoadDataList.Service.Resource.String.ApplicationName = global::LazyLoadDataList.Resource.String.ApplicationName;
			global::LazyLoadDataList.Service.Resource.String.Hello = global::LazyLoadDataList.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bar_bg_thin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dislike1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int stub = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int dataList = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int image = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int refreshButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int text1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataListItemLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
